[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  # Disable Git submodule fetching on Netlify
  GIT_SUBMODULES_DISABLE = "true"

[git]
  # Do not attempt to clone submodules
  submodules = false